### ISSUE TITLE
Plugin fails in M1 mac

### ISSUE THREAD

**Issue by squinonescolon** [pnmocap/neuron_mocap_live-blender#1]
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/steven/Library/Application Support/Blender/3.1/scripts/addons/neuron_mocap_live/__init__.py", line 3, in <module>
    from . import ops
  File "/Users/steven/Library/Application Support/Blender/3.1/scripts/addons/neuron_mocap_live/ops/__init__.py", line 5, in <module>
    from .mocap_connection import MocapConnect
  File "/Users/steven/Library/Application Support/Blender/3.1/scripts/addons/neuron_mocap_live/ops/mocap_connection.py", line 3, in <module>
    from ..mocap_api import *
  File "/Users/steven/Library/Application Support/Blender/3.1/scripts/addons/neuron_mocap_live/mocap_api/__init__.py", line 1, in <module>
    from .mocap_api import MCPError
  File "/Users/steven/Library/Application Support/Blender/3.1/scripts/addons/neuron_mocap_live/mocap_api/mocap_api.py", line 7, in <module>
    MocapApi = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), {
KeyError: 'Darwin'

**Comment by locobrain** [comment]
Mac is not supported for now, will be supported in the future
